version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./.docker/rabbitmq/.rabbitmq_data:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    env_file:
      - ./.env

  postgres-transactions:
    image: postgres:13
    container_name: postgres-transactions
    environment:
      POSTGRES_USER: ${POSTGRES_TRANSACTIONS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TRANSACTIONS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TRANSACTIONS_DB}
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgresql/transactions-data:/var/lib/postgresql/data
      - ./.docker/postgresql/transactions-init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  postgres-customers:
    image: postgres:13
    container_name: postgres-customers
    environment:
      POSTGRES_USER: ${POSTGRES_CLIENTS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_CLIENTS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_CLIENTS_DB}
    ports:
      - 5433:5432
    volumes:
      - ./.docker/postgresql/clients-data:/var/lib/postgresql/data
      - ./.docker/postgresql/clients-init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  transaction-ms:
    container_name: transaction-ms
    build:
      context: "./transactions-ms"
      dockerfile: Dockerfile
    command: npm run start:dev
    depends_on:
      - rabbitmq
      - postgres-transactions
    ports:
      - 3000:3000
    volumes:
      - ./transactions-ms:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./transactions-ms/.env

  customers:
    container_name: customers
    build:
      context: "./customers"
      dockerfile: Dockerfile
    command: npm run start:dev
    depends_on:
      - rabbitmq
      - postgres-customers
    ports:
      - 3001:3001
    volumes:
      - ./customers:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./customers/.env

  api-getway:
    container_name: api-getway
    build:
      context: "./api-getway"
      dockerfile: Dockerfile
    command: npm run start:dev
    depends_on:
      - rabbitmq
    ports:
      - 3002:3002
    volumes:
      - ./api-getway:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./api-getway/.env