global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3002']

  - job_name: 'customers'
    static_configs:
      - targets: ['customers:3001']

  - job_name: 'transactions'
    static_configs:
      - targets: ['transactions:3000']
