apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-geteway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-geteway
  template:
    metadata:
      name: api-geteway
      labels:
        app: api-geteway
    spec:
      containers:
      - name: api-geteway
        image: 054425168163.dkr.ecr.us-east-2.amazonaws.com/api-geteway:latest
        ports:
        - containerPort: 3002
        env:
          - name: CUSTOMERS
            value: "$(CUSTOMERS_SERVICE_HOST):3001"
          - name: TRANSACTIONS
            value: "$(TRANSACTIONS_SERVICE_HOST):3000"

---
apiVersion: v1
kind: Service
metadata:
  name: api-geteway-service
spec:
  type: ClusterIP
  selector:
    app: api-geteway
  ports:
    - name: http
      protocol: TCP
      port: 3002
      targetPort: 3002