name: API-GETEWAY-CI-CD

on:
  push:
    branches:
      - develop
    paths:
      - "api-geteway/src/**"
  workflow_dispatch:

jobs:
  API-GETEWAY-CI:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./api-geteway
          file: ./api-geteway/Dockerfile
          push: true
          tags: |
            054425168163.dkr.ecr.us-east-2.amazonaws.com/api-geteway:latest
            054425168163.dkr.ecr.us-east-2.amazonaws.com/api-geteway:v${{github.run_number}}


  API-GETEWAY-CD:
    runs-on: ubuntu-22.04
    needs: [API-GETEWAY-CI]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Kubeconfig
        run: echo "${{ secrets.K8S_CONFIG }}" | base64 -d > ~/.kube/config


      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          images: 054425168163.dkr.ecr.us-east-2.amazonaws.com/api-geteway:v${{github.run_number}}
          manifests: |
            k8s/api-geteway.yml
